name: Query Supabase

on:
  schedule:
    - cron: '0 0 */5 * *'  # každých 5 dní
  #workflow_dispatch:        # umožní ruční spuštění

jobs:
  query:
    runs-on: ubuntu-latest

    steps:
      - name: Query Supabase table
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Dotazuji tabulku 'events'..."
          curl -s -X GET "$SUPABASE_URL/rest/v1/drones?select=*" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -H "Content-Type: application/json"
